Invoking command in '/home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node': PYTHONPATH=/home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node/prefix_override:/home/cadt-02/Documents/can_test_usb/ros2_can/install/auto_node/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --editable --build-directory /home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node/build --no-deps install_data
Invoked command in '/home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node' returned '0': PYTHONPATH=/home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node/prefix_override:/home/cadt-02/Documents/can_test_usb/ros2_can/install/auto_node/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --editable --build-directory /home/cadt-02/Documents/can_test_usb/ros2_can/build/auto_node/build --no-deps install_data
