Invoking command in '/home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont': NX_CONNECTION=172.23.32.175 45142 172.23.34.34 4000 PYTHONPATH=/home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont/prefix_override:/home/cadt-02/Documents/can_test_usb/ros2_can/install/odometry_cont/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --editable --build-directory /home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont/build --no-deps install_data
Invoked command in '/home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont' returned '0': NX_CONNECTION=172.23.32.175 45142 172.23.34.34 4000 PYTHONPATH=/home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont/prefix_override:/home/cadt-02/Documents/can_test_usb/ros2_can/install/odometry_cont/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --editable --build-directory /home/cadt-02/Documents/can_test_usb/ros2_can/build/odometry_cont/build --no-deps install_data
